### PR TITLE
typo

### PR DESCRIPTION
**Pull request by aristretto**

### CODE REVIEW

**Comment by aristretto** [comment]
fixed a typo, and i guess my .editorconfig file stripped a lot of excess whitespace.

hope that helps!

**Comment by ireade** [comment]
Thank you! For some reason I always make errors!

**Comment by aristretto** [comment]
To err is human! I make plenty of them myself.

This is a cool, useful little project - thanks for putting it together!

**Comment by ireade** [comment]
Haha yes! And you're welcome :)

**Pull request merged**
